name: testU
on: push
jobs:

  super-lint: 
    name: Lint code base
    runs-on: ubuntu-lastest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Install dependencies + run tests
      run: |
        npm install 
        npm run build --if-present 
        npm test 
